# Generated by Django 3.0.3 on 2020-05-21 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_auto_20200521_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='liked',
        ),
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
