# Generated by Django 3.0.3 on 2020-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200422_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='comment',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
