# Generated by Django 3.0.3 on 2020-05-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200522_0018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
