# Generated by Django 3.0.3 on 2020-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200422_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_page', to='pages.Category'),
        ),
    ]
