# Generated by Django 3.0.3 on 2020-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200423_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='get_page', to='pages.Category'),
        ),
    ]
