# Generated by Django 3.0.3 on 2020-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200423_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
