# Generated by Django 3.0.3 on 2020-05-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
