# Generated by Django 3.0.3 on 2020-07-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_page_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
    ]
