# Generated by Django 3.0.3 on 2020-04-28 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0009_page_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='users',
            field=models.ManyToManyField(related_name='pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
