# Generated by Django 3.0.3 on 2020-04-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200427_1208'),
        ('pages', '0010_auto_20200428_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='users',
        ),
        migrations.AddField(
            model_name='page',
            name='profile',
            field=models.ManyToManyField(related_name='get_profiles', to='registration.Profile'),
        ),
    ]
