# Generated by Django 3.0.3 on 2020-04-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200428_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='profile',
            new_name='profiles',
        ),
    ]
