# Generated by Django 3.0.3 on 2020-04-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200428_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='profiles',
        ),
    ]
