# Generated by Django 3.0.3 on 2020-04-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_page_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='profiles',
        ),
    ]
