# Generated by Django 3.0.3 on 2020-04-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_comment_dislike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='users',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
