# Generated by Django 3.0.3 on 2020-05-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_page_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='likes',
        ),
    ]
