# Generated by Django 3.0.3 on 2020-05-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200429_1140'),
        ('pages', '0020_remove_page_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='registration.Profile'),
        ),
    ]
