# Generated by Django 3.0.3 on 2020-05-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200516_1158'),
        ('pages', '0021_auto_20200516_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_pofiles', to='registration.Profile'),
        ),
    ]
