# Generated by Django 3.0.3 on 2020-07-23 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200525_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ('-created',), 'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
        migrations.AddField(
            model_name='friendship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=1),
            preserve_default=False,
        ),
    ]
