# Generated by Django 3.0.3 on 2020-09-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200525_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
