# Generated by Django 3.0.3 on 2020-07-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_user_following'),
        ('registration', '0008_auto_20200723_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
