# Generated by Django 3.0.3 on 2020-04-28 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0003_auto_20200428_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='users',
            field=models.ManyToManyField(related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
